language: node_js
dist: trusty

node_js:
    - "6"

before_install:
  - mkdir $HOME/etcd
  - git clone https://github.com/coreos/etcd.git $HOME/etcd
  - (cd $HOME/etcd && git checkout -b v3.0.15 v3.0.15) 
  - (export GOPATH=$HOME/.go ; mkdir -p $GOPATH ; cd $HOME/etcd && go get && go build)

#install:

#script:
#    - npm install
#    - npm test
