language: node_js
#sudo: required
node_js:
    - "6"
dist: trusty

before_install:
  - mkdir $HOME/etcd
  - gimme 1.8.3
  - ls ~/.gimme/envs
  - source ~/.gimme/envs/go1.8.3.env
  - git clone https://github.com/coreos/etcd.git $HOME/etcd
  - (cd $HOME/etcd && git checkout -b v3.1.9 v3.1.9)
  - (export GOPATH=$HOME/.go ; mkdir -p $GOPATH ; cd $HOME/etcd && go get ; go build)

install:
    - nvm install 6

script:
    - npm install
    - npm test
